-- Ejecutar este script completo en el SQL Editor de Supabase
-- (Project > SQL Editor > New query > pegar > Run)
--
-- Esta tabla mapea nombres de malla (mesh) del modelo 3D
-- public/upper-limb-anatomy.glb a su nombre clínico en español y descripción.
-- El modelo es "Open3DModel - Upper limb" (AnatomyTOOL.org / RadboudUMC / LUMC),
-- licencia CC BY-SA 4.0. Varias mallas del modelo (partes de un mismo músculo,
-- huesos del carpo, falanges, etc.) apuntan a la misma fila mediante el
-- array mesh_names, para que la ficha mostrada sea la del músculo/hueso
-- completo aunque el clic caiga en una porción específica.

create table if not exists public.anatomy_structures (
  id bigint generated by default as identity primary key,
  mesh_names text[] not null,
  display_name text not null,
  type text not null, -- 'Hueso' | 'Musculo'
  description text not null,
  sources text[] default '{}',
  created_at timestamptz default now()
);

alter table public.anatomy_structures enable row level security;

create policy "Public read access"
  on public.anatomy_structures
  for select
  to anon, authenticated
  using (true);

insert into public.anatomy_structures (mesh_names, display_name, type, description, sources) values

-- ===== HUESOS =====

(array['Clavicle.r'], 'Clavícula', 'Hueso',
 'Hueso largo en forma de S que conecta el esternón con la escápula, formando el único puente óseo entre el miembro superior y el esqueleto axial. Es uno de los huesos que más se fractura, típicamente por una caída sobre el hombro o el brazo extendido.',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Gray''s Anatomy for Students']),

(array['Scapula.r.'], 'Escápula', 'Hueso',
 'Hueso plano triangular en la cara posterior del tórax, con la cavidad glenoidea que articula con la cabeza humeral. Su deslizamiento sobre la parrilla costal (ritmo escapulohumeral) es imprescindible para lograr el rango completo de elevación del brazo.',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Rouvière - Anatomía Humana']),

(array['Humerus.r'], 'Húmero', 'Hueso',
 'Hueso largo del brazo; su cabeza se articula con la glenoides (hombro) y su extremo distal con el radio y el cúbito (codo). El cuello quirúrgico y la diáfisis media (por su relación con el nervio radial) son sitios frecuentes de fractura.',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Gray''s Anatomy for Students']),

(array['Radius.r'], 'Radio', 'Hueso',
 'Hueso lateral del antebrazo (lado del pulgar). Rota alrededor del cúbito para producir la pronosupinación y transmite la mayor parte de la carga axial a través de la muñeca.',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Ulna.r'], 'Cúbito (Ulna)', 'Hueso',
 'Hueso medial del antebrazo (lado del meñique). Su olécranon forma la punta del codo y su escotadura troclear estabiliza la articulación húmero-cubital durante la flexo-extensión.',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Scaphoid.r', 'Lunate bone.r', 'Triquetrum.r', 'Pisiform.r', 'Trapezium.r', 'Trapezoid.r', 'Capitate.r', 'Hamate.r'],
 'Huesos del carpo', 'Hueso',
 'Ocho huesos cortos organizados en dos hileras: proximal (escafoides, semilunar, piramidal, pisiforme) y distal (trapecio, trapezoide, grande/capitate, ganchoso). El escafoides es el hueso del carpo que más se fractura y el de mayor riesgo de necrosis avascular por su vascularización retrógrada.',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Kaplan Anatomy Lecture Notes']),

(array['1st metacarpal bone.r', '2nd metacarpal bone.r', '3rd metacarpal bone.r', '4th metacarpal bone.r', '5th metacarpal bone.r'],
 'Metacarpianos', 'Hueso',
 'Cinco huesos largos que forman el esqueleto de la palma, entre el carpo y las falanges proximales. Sus cabezas distales forman los nudillos (articulaciones metacarpofalángicas).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array[
   'Proximal phalanx of 1st finger.r', 'Proximal phalanx of 2d finger.r', 'Proximal phalanx of 3rd finger.r', 'Proximal phalanx of 4th finger.r', 'Proximal phalanx of 5th finger.r',
   'Middle phalanx of 2d finger.r', 'Middle phalanx of 3rd finger.r', 'Middle phalanx of 4th finger.r', 'Middle phalanx of 5th finger.r',
   'Distal phalanx of 1st finger.r', 'Distal phalanx of 2d finger.r', 'Distal phalanx of 3d finger.r', 'Distal phalanx of 4th finger.r', 'Distal phalanx of 5th finger.r'
 ],
 'Falanges', 'Hueso',
 'Huesos largos de los dedos: del 2º al 5º dedo hay falange proximal, media y distal; el pulgar solo tiene proximal y distal. Sus articulaciones interfalángicas permiten la flexo-extensión fina necesaria para la prensión.',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

-- ===== MÚSCULOS DEL HOMBRO Y CINTURA ESCAPULAR =====

(array['Deltoid muscle.r', 'Acromial part of deltoid muscle.r', 'Clavicular part of deltoid muscle.r', 'Spinal part of deltoid muscle.r'],
 'Deltoides', 'Musculo',
 'Músculo de 3 porciones que recubre el hombro: la clavicular flexiona, la acromial (media) abduce y la espinal (posterior) extiende. Es el principal motor de la abducción de hombro a partir de los 15°. Inervación: nervio axilar (C5-C6).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Cael - Anatomía Funcional']),

(array['Supraspinatus muscle.r'], 'Supraespinoso', 'Musculo',
 'Músculo del manguito rotador; inicia y asiste los primeros 15° de abducción del hombro y estabiliza la cabeza humeral contra la glenoides. Es el tendón que más se rompe del manguito rotador, cerca de su inserción en el troquíter. Inervación: nervio supraescapular (C5-C6).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Gray''s Anatomy for Students']),

(array['Infraspinatus muscle.r'], 'Infraespinoso', 'Musculo',
 'Músculo del manguito rotador; produce la rotación externa del hombro y estabiliza la cabeza humeral. Inervación: nervio supraescapular (C5-C6).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Teres minor muscle.r'], 'Redondo menor', 'Musculo',
 'Músculo del manguito rotador; rotador externo del hombro, sinergista del infraespinoso. Inervación: nervio axilar (C5-C6).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Subscapularis muscle.r'], 'Subescapular', 'Musculo',
 'Músculo del manguito rotador ubicado en la cara anterior de la escápula; es el principal rotador interno del hombro y estabiliza anteriormente la articulación glenohumeral. Inervación: nervios subescapulares (C5-C6).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Teres major muscle.r'], 'Redondo mayor', 'Musculo',
 'Extiende, aduce y rota internamente el hombro; suele describirse como "el asistente del dorsal ancho" por compartir acción e inserción cercana. Inervación: nervio subescapular inferior (C5-C7).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Latissimus dorsi.r'], 'Dorsal ancho', 'Musculo',
 'Músculo extenso de la espalda; extiende, aduce y rota internamente el hombro. Clave en movimientos de tracción (remo, dominadas). Inervación: nervio toracodorsal (C6-C8).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Cael - Anatomía Funcional']),

(array['Pectoralis major.r', 'Clavicular head of pectoralis major muscle.r', 'Sternocostal head of pectoralis major muscle.r', 'Abdominal head of pectoralis major muscle.r'],
 'Pectoral mayor', 'Musculo',
 'Músculo de 3 cabezas (clavicular, esternocostal, abdominal) que aduce y rota internamente el hombro; la porción clavicular también flexiona. Inervación: nervios pectorales medial y lateral (C5-T1).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Pectoralis minor muscle.r'], 'Pectoral menor', 'Musculo',
 'Desciende y estabiliza la escápula, y asiste la elevación de las costillas en la inspiración forzada. Su acortamiento se asocia a síndrome de pinzamiento del desfiladero torácico. Inervación: nervio pectoral medial (C8-T1).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Serratus anterior muscle.r'], 'Serrato anterior', 'Musculo',
 'Protrae y rota ascendentemente la escápula, manteniéndola apoyada contra la parrilla costal. Su parálisis (lesión del nervio torácico largo) produce la clásica "escápula alada". Inervación: nervio torácico largo (C5-C7).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Gray''s Anatomy for Students']),

(array['Trapezius muscle.r', 'Ascending part of Trapezius muscle.r', 'Descending part of Trapezius muscle.r', 'Transverse part of trapezius muscle.r'],
 'Trapecio', 'Musculo',
 'Músculo de 3 porciones: la descendente eleva la escápula, la transversa la retrae y la ascendente la deprime; en conjunto rotan ascendentemente la escápula durante la elevación del brazo. Inervación: nervio accesorio espinal (XI par craneal).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Rhomboid major muscle.r', 'Rhomboid minor muscle.r'],
 'Romboides', 'Musculo',
 'Retraen y elevan levemente la escápula, fijándola contra la parrilla costal; antagonistas del serrato anterior en la rotación escapular. Inervación: nervio dorsal escapular (C4-C5).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Levator scapulae.r'], 'Elevador de la escápula', 'Musculo',
 'Eleva la escápula y, junto con el trapecio, ayuda a extender/lateralizar el cuello. Frecuentemente implicado en cervicalgias por tensión muscular. Inervación: nervio dorsal escapular y ramas cervicales (C3-C5).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Subclavius muscle.r'], 'Subclavio', 'Musculo',
 'Pequeño músculo entre la clavícula y la 1ª costilla; estabiliza y deprime levemente la articulación esternoclavicular, y protege el paquete neurovascular subyacente. Inervación: nervio subclavio (C5-C6).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Coracobrachialis muscle.r'], 'Coracobraquial', 'Musculo',
 'Flexiona y aduce débilmente el hombro; suele usarse como referencia quirúrgica porque el nervio musculocutáneo lo perfora. Inervación: nervio musculocutáneo (C5-C7).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

-- ===== MÚSCULOS DEL BRAZO =====

(array['Long head of biceps brachii.r', 'Short head of biceps brachii.r', 'Common tendon of biceps brachii.r'],
 'Bíceps braquial', 'Musculo',
 'Músculo de 2 cabezas; flexiona el codo y es el supinador más potente del antebrazo, especialmente con el codo flexionado. La tendinopatía de la porción larga (en la corredera bicipital) suele asociarse a patología del manguito rotador. Inervación: nervio musculocutáneo (C5-C6).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Cael - Anatomía Funcional']),

(array['Brachialis muscle.r'], 'Braquial anterior', 'Musculo',
 'Principal flexor del codo, independiente de la posición del antebrazo (a diferencia del bíceps). Inervación: nervio musculocutáneo (C5-C6).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Long head of triceps brachii.r', 'Lateral head of triceps brachii.r', 'Medial head of triceps brachii.r', 'Common tendon of triceps brachii.r'],
 'Tríceps braquial', 'Musculo',
 'Músculo de 3 cabezas en la cara posterior del brazo; único extensor potente del codo. La cabeza larga también asiste la extensión y aducción del hombro. Inervación: nervio radial (C6-C8).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Anconeus muscle.r'], 'Ancóneo', 'Musculo',
 'Pequeño músculo posterolateral del codo; asiste la extensión y dinamiza/estabiliza la articulación durante el movimiento. Inervación: nervio radial (C7-C8, T1).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Brachioradialis muscle.r'], 'Braquiorradial', 'Musculo',
 'Flexor accesorio del codo, más activo cuando el antebrazo está en posición neutra (ni pronado ni supinado). Inervación: nervio radial (C5-C6).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

-- ===== MÚSCULOS DEL ANTEBRAZO =====

(array['Humeral head of pronator teres.r', 'Ulnar head of pronator teres.r'],
 'Pronador redondo', 'Musculo',
 'Origen en el epicóndilo medial (epitróclea); pronador principal del antebrazo y flexor accesorio del codo. Su hipertrofia/tensión puede comprimir el nervio mediano (síndrome del pronador redondo). Inervación: nervio mediano (C6-C7).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Pronator quadratus.r'], 'Pronador cuadrado', 'Musculo',
 'Músculo profundo distal del antebrazo; pronador principal en movimientos rápidos o con el codo extendido. Inervación: nervio mediano/interóseo anterior (C8-T1).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Supinator.r'], 'Supinador', 'Musculo',
 'Rodea la porción proximal del radio; supina el antebrazo junto con el bíceps braquial. El nervio radial (rama interósea posterior) lo atraviesa y puede comprimirse ahí (síndrome del túnel radial). Inervación: nervio radial (C5-C6).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Flexor carpi radialis.r'], 'Flexor radial del carpo', 'Musculo',
 'Flexiona y desvía radialmente la muñeca. Origen en el epicóndilo medial. Inervación: nervio mediano (C6-C7).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Humeral head of flexor carpi ulnaris.r', 'Ulnar head of flexor carpi ulnaris.r', 'Common tendon of flexor carpi ulnaris.r'],
 'Flexor cubital del carpo', 'Musculo',
 'Flexiona y desvía cubitalmente la muñeca. El nervio cubital pasa entre sus dos cabezas, sitio de posible compresión distal al codo. Inervación: nervio cubital (C7-T1).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Palmaris longus muscle.r'], 'Palmar largo', 'Musculo',
 'Tensa la aponeurosis palmar; ausente congénitamente hasta en ~15% de la población sin repercusión funcional. Inervación: nervio mediano (C7-C8).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Flexor digitorum superficialis humero-ulnar head.r', 'Flexor digitorum superficialis radial head.r'],
 'Flexor superficial de los dedos', 'Musculo',
 'Flexiona las articulaciones interfalángicas proximales del 2º al 5º dedo (y asiste la flexión de muñeca y metacarpofalángicas). Inervación: nervio mediano (C7-T1).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Flexor digitorum profundus.r'], 'Flexor profundo de los dedos', 'Musculo',
 'Único flexor de las articulaciones interfalángicas distales del 2º al 5º dedo. Inervación mixta: nervio mediano (2º-3º dedo) y nervio cubital (4º-5º dedo).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Flexor pollicis longus.r'], 'Flexor largo del pulgar', 'Musculo',
 'Único flexor de la articulación interfalángica del pulgar. Inervación: nervio mediano/interóseo anterior (C8-T1).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Extensor carpi radialis longus.r'], 'Extensor radial largo del carpo', 'Musculo',
 'Extiende y desvía radialmente la muñeca. Origen en la cresta supracondílea lateral del húmero. Inervación: nervio radial (C6-C7).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Extensor carpi radialis brevis.r'], 'Extensor radial corto del carpo', 'Musculo',
 'Extiende la muñeca; su origen en el epicóndilo lateral es el sitio más frecuentemente afectado en la epicondilitis lateral ("codo de tenista"). Inervación: nervio radial (C7-C8).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Gray''s Anatomy for Students']),

(array['Humeral head of extensor carpi ulnaris.r', 'Ulnar head of extensor carpi ulnaris.r', 'Common tendon of extensor carpi ulnaris.r'],
 'Extensor cubital del carpo', 'Musculo',
 'Extiende y desvía cubitalmente la muñeca. Inervación: nervio radial/interóseo posterior (C7-C8).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Extensor digitorum.r'], 'Extensor de los dedos', 'Musculo',
 'Extiende las articulaciones metacarpofalángicas y, mediante el aparato extensor, asiste la extensión interfalángica del 2º al 5º dedo. Inervación: nervio radial/interóseo posterior (C7-C8).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Extensor digiti minimi.r'], 'Extensor propio del meñique', 'Musculo',
 'Extensor accesorio del 5º dedo, independiente del extensor común. Inervación: nervio radial/interóseo posterior (C7-C8).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Extensor indicis.r'], 'Extensor propio del índice', 'Musculo',
 'Extensor accesorio del 2º dedo (índice), permite extenderlo de forma independiente de los demás. Inervación: nervio radial/interóseo posterior (C7-C8).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Abductor pollicis longus.r'], 'Abductor largo del pulgar', 'Musculo',
 'Abduce y extiende el 1º metacarpiano; forma, junto al extensor corto del pulgar, el primer compartimento extensor (afectado en la tenosinovitis de De Quervain). Inervación: nervio radial/interóseo posterior (C7-C8).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Extensor pollicis brevis.r'], 'Extensor corto del pulgar', 'Musculo',
 'Extiende la articulación metacarpofalángica del pulgar. Comparte el primer compartimento extensor con el abductor largo del pulgar. Inervación: nervio radial/interóseo posterior (C7-C8).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Extensor pollicis longus.r'], 'Extensor largo del pulgar', 'Musculo',
 'Extiende la articulación interfalángica del pulgar. Ocupa el tercer compartimento extensor, angulándose alrededor del tubérculo de Lister. Inervación: nervio radial/interóseo posterior (C7-C8).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

-- ===== MÚSCULOS INTRÍNSECOS DE LA MANO =====

(array['Abductor pollicis brevis.r', 'Deep head of flexor pollicis brevis.r', 'Superficial head of flexor pollicis brevis.r', 'Opponens pollicis muscle.r'],
 'Músculos tenares', 'Musculo',
 'Grupo de músculos en la base del pulgar (abductor corto, flexor corto y oponente) responsables de los movimientos finos del pulgar, en especial la oposición. Su atrofia es un signo característico y tardío del síndrome del túnel carpiano. Inervación: nervio mediano.',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Kaplan Anatomy Lecture Notes']),

(array['Oblique head of adductor pollicis.r', 'Transverse head of adductor pollicis.r'],
 'Aductor del pulgar', 'Musculo',
 'Aduce el pulgar hacia la palma; principal músculo de la fuerza de pinza entre el pulgar y el índice. Inervación: nervio cubital (rama profunda).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['Abductor digiti minimi.r', 'Flexor digiti minimi brevis of hand.r', 'Opponens digiti minimi muscle of hand.r', 'Palmaris brevis muscle.r'],
 'Músculos hipotenares', 'Musculo',
 'Grupo de músculos en la base del 5º dedo (abductor, flexor corto, oponente y palmar cutáneo) que permiten sus movimientos finos y ahuecan la palma. Inervación: nervio cubital.',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['1st dorsal interosseus of hand.r', '2nd dorsal interosseus of hand.r', '3rd dorsal interosseus of hand.r', '4th dorsal interosseus of hand.r'],
 'Interóseos dorsales', 'Musculo',
 'Abducen los dedos respecto al eje del 3º dedo (separan los dedos) y asisten la flexión metacarpofalángica con extensión interfalángica. Inervación: nervio cubital (rama profunda).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['1st palmar interosseus of hand.r', '2nd palmar interosseus of hand.r', '3rd palmar interosseus of hand.r'],
 'Interóseos palmares', 'Musculo',
 'Aducen los dedos hacia el eje del 3º dedo (juntan los dedos) y asisten la flexión metacarpofalángica con extensión interfalángica. Inervación: nervio cubital (rama profunda).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']),

(array['1st lumbrical of hand.r', '2nd lumbrical of hand.r', '3rd lumbrical of hand.r', '4th lumbrical of hand.r'],
 'Lumbricales', 'Musculo',
 'Flexionan las articulaciones metacarpofalángicas mientras extienden las interfalángicas, coordinando el movimiento de "garra funcional" de la mano. Inervación mixta: nervio mediano (1º-2º) y nervio cubital (3º-4º).',
 array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)']);
