-- Ejecutar este script completo en el SQL Editor de Supabase
-- (Project > SQL Editor > New query > pegar > Run)

create table if not exists public.bibliography_topics (
  id bigint generated by default as identity primary key,
  title text not null,
  region text not null,
  summary text,
  bones text[] default '{}',
  ligaments text[] default '{}',
  muscles text[] default '{}',
  nerves text[] default '{}',
  movements text[] default '{}',
  clinical_relevance text[] default '{}',
  sources text[] default '{}',
  created_at timestamptz default now()
);

alter table public.bibliography_topics enable row level security;

create policy "Public read access"
  on public.bibliography_topics
  for select
  to anon, authenticated
  using (true);

insert into public.bibliography_topics
  (title, region, summary, bones, ligaments, muscles, nerves, movements, clinical_relevance, sources)
values
(
  'Complejo Articular del Hombro',
  'Miembro Superior',
  'La articulación más móvil del cuerpo, resultado de la acción coordinada de cuatro articulaciones (glenohumeral, acromioclavicular, esternoclavicular y escapulotorácica) que priorizan el rango de movimiento a costa de la estabilidad.',
  array['Húmero (cabeza humeral)', 'Escápula (cavidad glenoidea, acromion, apófisis coracoides, espina escapular)', 'Clavícula'],
  array['Ligamentos glenohumerales superior, medio e inferior', 'Ligamento coracohumeral', 'Ligamento coracoacromial', 'Ligamento acromioclavicular', 'Ligamentos coracoclaviculares (conoide y trapezoide)', 'Ligamentos esternoclaviculares'],
  array[
    'Deltoides — abducción (porción media), flexión (anterior), extensión (posterior) de hombro — nervio axilar (C5-C6)',
    'Supraespinoso — inicia/asiste la abducción y estabiliza la cabeza humeral — nervio supraescapular (C5-C6)',
    'Infraespinoso — rotación externa — nervio supraescapular (C5-C6)',
    'Redondo menor — rotación externa — nervio axilar (C5-C6)',
    'Subescapular — rotación interna, estabiliza anteriormente — nervio subescapular (C5-C6)',
    'Trapecio — eleva, retrae y rota la escápula — nervio accesorio espinal (XI par craneal)',
    'Serrato anterior — protracción y rotación ascendente de la escápula — nervio torácico largo (C5-C7)',
    'Dorsal ancho — extensión, aducción y rotación interna — nervio toracodorsal (C6-C8)',
    'Pectoral mayor — aducción y rotación interna — nervios pectorales medial y lateral (C5-T1)'
  ],
  array[]::text[],
  array['Flexión: 0-180°', 'Extensión: 0-60°', 'Abducción: 0-180°', 'Rotación interna: 0-70°', 'Rotación externa: 0-90°', 'Ritmo escapulohumeral aproximado de 2:1 entre movimiento glenohumeral y escapulotorácico durante la elevación'],
  array[
    'Síndrome de pinzamiento subacromial: compresión de los tendones del manguito rotador (sobre todo supraespinoso) contra el arco coracoacromial',
    'Rotura del manguito rotador: más frecuente en el tendón del supraespinoso, cerca de su inserción en el troquíter',
    'Capsulitis adhesiva (hombro congelado): pérdida progresiva y dolorosa del rango activo y pasivo',
    'Inestabilidad glenohumeral: predominantemente anterior, dada la escasa congruencia ósea de la articulación',
    'Tendinopatía del bíceps (porción larga): dolor en la corredera bicipital, frecuentemente asociada a patología del manguito rotador'
  ],
  array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Gray''s Anatomy for Students', 'Cael - Anatomía Funcional', 'Tortora & Derrickson - Principios de Anatomía y Fisiología (13ª ed.)']
),
(
  'Articulación del Codo',
  'Miembro Superior',
  'Articulación compuesta (húmero-cubital, húmero-radial y radiocubital proximal) que combina flexo-extensión con la pronosupinación del antebrazo, con gran estabilidad ósea y ligamentaria.',
  array['Húmero (tróclea, cóndilo, epicóndilo medial y lateral)', 'Cúbito/ulna (olécranon, apófisis coronoides, escotadura troclear)', 'Radio (cabeza radial, cuello)'],
  array['Ligamento colateral cubital (medial)', 'Ligamento colateral radial (lateral)', 'Ligamento anular del radio'],
  array[
    'Bíceps braquial — flexión de codo y supinación del antebrazo — nervio musculocutáneo (C5-C6)',
    'Braquial anterior — principal flexor del codo — nervio musculocutáneo (C5-C6)',
    'Braquiorradial — flexor accesorio, más activo en posición neutra — nervio radial (C5-C6)',
    'Tríceps braquial — extensión del codo — nervio radial (C6-C8)',
    'Ancóneo — asiste la extensión y estabiliza la articulación — nervio radial (C7-C8, T1)',
    'Pronador redondo — origen en el epicóndilo medial, pronación del antebrazo — nervio mediano (C6-C7)',
    'Supinador — supinación del antebrazo — nervio radial/interóseo posterior (C5-C6)'
  ],
  array[]::text[],
  array['Flexión: 0-150°', 'Extensión: 0° (hiperextensión fisiológica leve en algunos individuos)', 'Ángulo de carga (valgo fisiológico) en extensión completa: aproximadamente 10-15°'],
  array[
    'Epicondilitis lateral ("codo de tenista"): tendinopatía de los extensores de muñeca en su origen, principalmente el extensor radial corto del carpo',
    'Epicondilitis medial ("codo de golfista"): tendinopatía de los flexores-pronadores en el epicóndilo medial',
    'Neuropatía cubital en el codo (túnel cubital): el nervio cubital es superficial y vulnerable al pasar posterior al epicóndilo medial',
    'Bursitis olecraneana: inflamación de la bolsa serosa superficial al olécranon',
    'Fractura de cabeza radial: lesión frecuente por caída con el brazo en extensión'
  ],
  array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Rouvière - Anatomía Humana', 'Gray''s Anatomy for Students']
),
(
  'Antebrazo y Articulación Radiocubital',
  'Miembro Superior',
  'El antebrazo permite la pronosupinación gracias a la rotación del radio alrededor del cúbito, coordinada entre las articulaciones radiocubital proximal y distal y conectada por la membrana interósea.',
  array['Radio', 'Cúbito/Ulna', 'Membrana interósea antebraquial'],
  array['Ligamento anular del radio (radiocubital proximal)', 'Complejo del fibrocartílago triangular (radiocubital distal)', 'Membrana interósea (conecta radio y cúbito, transmite carga)'],
  array[
    'Pronador redondo y pronador cuadrado — pronación — nervio mediano (C6-C7 y C8-T1 respectivamente)',
    'Supinador y bíceps braquial — supinación — nervio radial y nervio musculocutáneo respectivamente'
  ],
  array[]::text[],
  array['Pronación: 0-80°', 'Supinación: 0-80°', 'Eje de rotación desde la cabeza radial hasta la cabeza cubital (cúpula del cúbito)'],
  array[
    'Fractura de Monteggia: fractura de cúbito proximal con luxación de la cabeza radial',
    'Fractura de Galeazzi: fractura de radio distal con luxación de la articulación radiocubital distal',
    'Lesiones del fibrocartílago triangular: causa frecuente de dolor cubital de muñeca, especialmente en deportes de carga axial',
    'Sinostosis radiocubital congénita: limita severamente la pronosupinación'
  ],
  array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Rouvière - Anatomía Humana']
),
(
  'Muñeca (Radiocarpiana y Carpo)',
  'Miembro Superior',
  'Complejo articular formado por el radio distal, el fibrocartílago triangular y las dos hileras de huesos del carpo, fundamental para orientar la mano en el espacio.',
  array['Radio distal', 'Hilera proximal del carpo: escafoides, semilunar, piramidal, pisiforme', 'Hilera distal del carpo: trapecio, trapezoide, grande (capitate), ganchoso'],
  array['Ligamento radiocarpiano dorsal y palmar', 'Ligamento colateral radial del carpo', 'Ligamento colateral cubital del carpo', 'Ligamentos intercarpianos (interóseos)', 'Retináculo flexor (techo del túnel carpiano)'],
  array[
    'Flexor radial del carpo — flexión de muñeca — nervio mediano',
    'Flexor cubital del carpo — flexión de muñeca — nervio cubital',
    'Extensor radial largo y corto del carpo — extensión de muñeca — nervio radial',
    'Extensor cubital del carpo — extensión de muñeca — nervio radial',
    'Palmar largo — tensor de la aponeurosis palmar (ausente hasta en ~15% de la población) — nervio mediano'
  ],
  array[]::text[],
  array['Flexión: 0-80°', 'Extensión: 0-70°', 'Desviación radial: 0-20°', 'Desviación cubital: 0-30°'],
  array[
    'Síndrome del túnel carpiano: compresión del nervio mediano bajo el retináculo flexor; la neuropatía compresiva más frecuente del miembro superior',
    'Fractura de escafoides: alto riesgo de necrosis avascular por su vascularización retrógrada, con frecuencia subdiagnosticada tras una caída con la mano extendida',
    'Inestabilidad escafolunar: lesión ligamentaria que puede evolucionar a un patrón de colapso conocido como SLAC (scapholunate advanced collapse)',
    'Tenosinovitis de De Quervain: inflamación del primer compartimento extensor (abductor largo y extensor corto del pulgar)'
  ],
  array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Kaplan Anatomy Lecture Notes', 'Gray''s Anatomy for Students']
),
(
  'Mano: Articulaciones y Arcos',
  'Miembro Superior',
  'Estructura altamente especializada, organizada en arcos óseos (longitudinal, transverso proximal y transverso distal) que permiten adaptarse a la prensión de objetos de formas muy diversas.',
  array['Metacarpianos (I a V)', 'Falanges proximales, medias y distales', 'Sesamoideos del pulgar'],
  array['Ligamentos colaterales de las articulaciones metacarpofalángicas e interfalángicas', 'Ligamento colateral cubital de la metacarpofalángica del pulgar (lesión del esquiador/guardabosque)', 'Placas volares'],
  array[
    'Interóseos dorsales — abducción de los dedos — nervio cubital',
    'Interóseos palmares — aducción de los dedos — nervio cubital',
    'Lumbricales — flexión metacarpofalángica con extensión interfalángica — nervio mediano (1º y 2º) y cubital (3º y 4º)',
    'Músculos tenares (abductor corto, flexor corto, oponente del pulgar) — movimientos del pulgar — nervio mediano',
    'Músculos hipotenares (abductor, flexor corto, oponente del meñique) — movimientos del 5º dedo — nervio cubital',
    'Flexor superficial y profundo de los dedos — flexión de falanges — nervio mediano (y cubital para el 4º-5º dedo del flexor profundo)',
    'Extensor de los dedos — extensión de falanges — nervio radial'
  ],
  array[]::text[],
  array['Flexión metacarpofalángica: 0-90°', 'Flexión interfalángica proximal: 0-100°', 'Flexión interfalángica distal: 0-80°', 'Oposición del pulgar: movimiento compuesto propio de la articulación trapeciometacarpiana (en silla de montar)'],
  array[
    'Dedo en martillo (mallet finger): avulsión o rotura del tendón extensor en su inserción distal',
    'Dedo en resorte (trigger finger): estenosis de la polea A1 que atrapa el tendón flexor',
    'Contractura de Dupuytren: engrosamiento y retracción de la fascia palmar, más frecuente en 4º y 5º dedo',
    'Rizartrosis: artrosis de la articulación trapeciometacarpiana del pulgar, muy frecuente y limitante para la pinza'
  ],
  array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Rouvière - Anatomía Humana', 'McMinn - Gran Atlas de Anatomía']
),
(
  'Plexo Braquial',
  'Miembro Superior',
  'Red nerviosa formada por las ramas ventrales de C5 a T1, organizada en raíces, troncos, divisiones, fascículos y ramas terminales, que inerva la totalidad del miembro superior.',
  array[]::text[],
  array[]::text[],
  array[]::text[],
  array[
    'Raíces: C5, C6, C7, C8, T1',
    'Troncos: superior (C5-C6), medio (C7), inferior (C8-T1)',
    'Divisiones: cada tronco se divide en una división anterior y una posterior',
    'Fascículos: lateral, medial y posterior (nombrados según su relación con la arteria axilar)',
    'Nervio musculocutáneo (fascículo lateral, C5-C7) — inerva los flexores del brazo (bíceps, braquial, coracobraquial)',
    'Nervio mediano (fascículos lateral y medial, C6-T1) — inerva la mayoría de los flexores del antebrazo y los músculos tenares',
    'Nervio cubital/ulnar (fascículo medial, C8-T1) — inerva flexor cubital del carpo, flexor profundo de los dedos (mitad cubital) y la mayoría de los músculos intrínsecos de la mano',
    'Nervio radial (fascículo posterior, C5-T1) — inerva todos los extensores del brazo y antebrazo',
    'Nervio axilar (fascículo posterior, C5-C6) — inerva deltoides y redondo menor',
    'Nervio supraescapular (tronco superior, C5-C6) — inerva supraespinoso e infraespinoso',
    'Nervio torácico largo (raíces C5-C7) — inerva serrato anterior; su lesión produce escápula alada'
  ],
  array[]::text[],
  array[
    'Parálisis de Erb-Duchenne (C5-C6): lesión obstétrica o traumática alta; produce el clásico "brazo del mesero" (hombro en rotación interna, codo en extensión)',
    'Parálisis de Klumpke (C8-T1): lesión baja del plexo, afecta principalmente la musculatura intrínseca de la mano',
    'Lesiones por tracción (ej. accidentes con abducción forzada del brazo): pueden producir avulsiones radiculares con mal pronóstico de recuperación',
    'La exploración sistemática de miotomas y dermatomas es clave para localizar el nivel de la lesión dentro del plexo'
  ],
  array['Latarjet - Anatomía Humana, Tomo 1 (4ª ed.)', 'Neuroanatomía Clínica, Snell (7ª ed.)', 'Fitzgerald - Neuroanatomía Clínica y Neurociencia']
);
